name: salert
description: Library for sales calculations.
version: 0.0.1
repository: https://github.com/h4j4x/salert

environment:
  sdk: ^3.4.0

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: any
